export enum Prefixes {
  apiKeys = '[ApiKeys]',
  ingredients = '[Ingredients]',
  ozaSupplies = '[OzaSupplies]',
  photos = '[Photos]',
  recipes = '[Recipes]',
  seasons = '[Seasons]',
  settings = '[Settings]',
  tags = '[Tags]',
  timers = '[Timers]',
}

export enum Actions {
  add = 'Add',
  addError = 'Add Error',
  addFromRecipe = 'Add From Recipe',
  addSuccess = 'Add Success',
  changeOzaKey = 'Change OZA Key',
  delete = 'Delete',
  deleteError = 'Delete Error',
  deleteSuccess = 'Delete Success',
  keyNotExists = 'Key not exists',
  load = 'Load',
  loadError = 'Load Error',
  loadSuccess = 'Load Success',
  reorder = 'Reorder',
  reset = 'Reset',
  switchAutocomplete = 'Switch Autocomplete',
  update = 'Update',
  updateAvailable = 'Update Available',
  updateError = 'Update Error',
  updateFavourite = 'Update Favourite',
  updateName = 'Update Name',
  updateOzaId = 'Update Oza Id',
  updateSuccess = 'Update Success',
  updateToDo = 'Update ToDo',
}
