export enum RoutingConfig {
  account = 'account',
  any = '**',
  changePassword = 'change-password/:token',
  create = 'create',
  favourite = 'favourites',
  fb = 'fb',
  home = '',
  ingredientRecipes = ':id/recipes',
  ingredients = 'ingredients',
  login = 'login',
  notFound = 'notFound',
  publicRecipe = 'public/recipes/:id',
  recipe = ':id',
  recipeEdit = ':id/edit',
  recipes = 'recipes',
  registration = 'registration',
  resetPassword = 'reset-password',
  seasons = 'seasons',
  tagRecipes = ':id/recipes',
  tags = 'tags',
  toDo = 'to-do',
}
