export enum RoutingConfig {
  any = '**',
  login = 'login',
  changePassword = 'change-password/:token',
  resetPassword = 'reset-password',
  registration = 'registration',
  home = '',
  tags = 'tags',
  recipes = 'recipes',
  ingredients = 'ingredients',
  seasons = 'seasons',
  create = 'create',
  favourite = 'favourites',
  toDo = 'to-do',
  tagRecipes = ':id/recipes',
  notFound = 'notFound',
  recipe = ':id',
  ingredientRecipes = ':id/recipes',
  recipeEdit = ':id/edit',
  fb = 'fb',
  account = 'account',
  publicRecipe = 'public/recipes/:id'
}
